<script setup lang="ts">
import { ArrowRight, BellRing, Building2, ChartNoAxesCombined, Check, Heart, House, Mail, MessageCircle, Search, ShieldCheck } from 'lucide-vue-next'
const features = [
  { icon: Search, eyebrow: 'DISCOVERY', title: 'Search that feels natural', body: 'Find published properties by title, city, community, purpose, type, price, bedroom count, and floor area. Sort by price or size, then keep scrolling as more results load.' },
  { icon: House, eyebrow: 'LISTINGS', title: 'More than homes', body: 'Browse residential, commercial, industrial, land, rental, and short-stay listings with pricing and practical property details.' },
  { icon: Heart, eyebrow: 'PERSONAL', title: 'Saved places and searches', body: 'Keep a shortlist of favorite properties and save search filters. Switch alerts on or off from Saved Searches.' },
  { icon: MessageCircle, eyebrow: 'COMMUNICATION', title: 'Inquiries with context', body: 'Ask about a property, share a phone number, arrange a viewing, and continue the conversation in the property-linked inbox.' },
  { icon: ShieldCheck, eyebrow: 'TEAM ACCESS', title: 'Permissions for each role', body: 'Organization admins control member roles. Agents work their assigned leads, while managers can review team sales activity.' },
  { icon: Building2, eyebrow: 'OPERATIONS', title: 'Property operations together', body: 'Manage portfolios, units, leases, rent entries, maintenance work, vendors, development inventory, and owner statements.' },
  { icon: BellRing, eyebrow: 'EMAIL UPDATES', title: 'Notifications when SMTP is ready', body: 'New inbox messages can notify the other participant by email. Daily saved-search digests can send newly matching listings at 9:00 AM Pakistan time. Configure SMTP to deliver them.' },
  { icon: ChartNoAxesCombined, eyebrow: 'REPORTING', title: 'Keep a view of the work', body: 'Workspace summaries cover leads, viewings, offers, rent, maintenance, development reservations, income, expenses, and payouts.' },
]
</script>
<template><div class="marketing-page page-container"><section class="marketing-intro"><div class="eyebrow muted-eyebrow">THE PROPSPHERE PLATFORM</div><h1>The tools around the property, all connected.</h1><p>Explore the marketplace, keep conversations moving, and manage the work that follows.</p><div class="marketing-actions"><RouterLink class="button button-primary" to="/signup">Create an account <ArrowRight :size="16"/></RouterLink><RouterLink class="button button-outline" to="/plans">Compare plans</RouterLink></div></section><div class="feature-grid"><article v-for="feature in features" :key="feature.title" class="feature-card"><div class="feature-card-top"><span><component :is="feature.icon" :size="19"/></span><small>{{feature.eyebrow}}</small></div><h2>{{feature.title}}</h2><p>{{feature.body}}</p></article></div><section class="marketing-callout feature-callout"><div><Mail :size="20"/><span><b>Saved-search and inbox emails</b><small>Email delivery is optional and requires SMTP settings on the PropSphere server.</small></span></div><RouterLink class="button button-dark" to="/contact">Ask about setup</RouterLink></section><p class="feature-footnote"><Check :size="14"/> Email alerts remain manageable: saved-search notifications can be switched on or off individually.</p></div></template>
