<script setup lang="ts">
import { ArrowRight, Check, CircleHelp, Crown, House, Users } from 'lucide-vue-next'
const plans = [
  { name: 'Explore', icon: House, eyebrow: 'FOR BUYERS & RENTERS', title: 'Start with the marketplace', description: 'Browse listings and build your shortlist at your own pace.', items: ['Search and filter listings', 'Save favorite properties', 'Create a buyer, renter, or owner account'], action: 'Create free account', to: '/signup', featured: false },
  { name: 'Workspace', icon: Users, eyebrow: 'FOR OWNERS & SMALL TEAMS', title: 'Keep property work together', description: 'A private workspace for listings, customers, and day-to-day property operations.', items: ['Submit and review property listings', 'Manage leads, viewings, and conversations', 'Track portfolios, leases, rent, and maintenance'], action: 'Talk about a workspace', to: '/contact?topic=Workspace%20plans', featured: true },
  { name: 'Business', icon: Crown, eyebrow: 'FOR GROWING ORGANIZATIONS', title: 'Shape the right team setup', description: 'Discuss roles, property operations, and onboarding for your organization.', items: ['Admin-managed team permissions', 'Sales manager team visibility', 'Development and finance workflows'], action: 'Contact our team', to: '/contact?topic=Business%20plans', featured: false },
]
</script>
<template><div class="marketing-page page-container"><section class="marketing-intro plans-intro"><div class="eyebrow muted-eyebrow">PLANS & SUBSCRIPTIONS</div><h1>A setup that fits how you work with property.</h1><p>Start exploring for free. If you manage listings or a team, talk with us about a workspace plan that fits your needs.</p></section><div class="plan-grid"><article v-for="plan in plans" :key="plan.name" class="plan-card" :class="{'plan-featured':plan.featured}"><div class="plan-icon"><component :is="plan.icon" :size="20"/></div><div class="eyebrow muted-eyebrow">{{plan.eyebrow}}</div><h2>{{plan.name}}</h2><h3>{{plan.title}}</h3><p>{{plan.description}}</p><ul><li v-for="item in plan.items" :key="item"><Check :size="15"/>{{item}}</li></ul><RouterLink :class="plan.featured?'button button-primary':'button button-outline'" :to="plan.to">{{plan.action}} <ArrowRight :size="15"/></RouterLink></article></div><section class="subscription-note"><CircleHelp :size="19"/><p><b>About subscription billing</b><br/>The current PropSphere app supports rent payments and optional Safepay checkout. Recurring platform-plan billing is not switched on yet; contact us for plan details rather than entering payment information here.</p></section></div></template>
