<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CalendarDays, Clock3, Video } from 'lucide-vue-next'
import { api } from '../api'
import { useSessionStore } from '../stores/session'
const session = useSessionStore()
const canRequest = computed(() => ['BUYER','TENANT'].includes(session.session?.user.role || ''))
const viewings = ref<any[]>([])
const properties = ref<any[]>([])
const loading = ref(true)
const saving = ref(false)
const error = ref('')
const form = ref({ propertyId: '', scheduledAt: '', mode: 'IN_PERSON', notes: '' })
async function load() { loading.value = true; try { const [v,p] = await Promise.all([api.get('/viewings'), api.get('/properties')]); viewings.value = v.data; properties.value = p.data; if (!form.value.propertyId && p.data.length) form.value.propertyId=p.data[0].id } catch (e:any) { error.value = e.response?.data?.message || 'Could not load viewings.' } finally { loading.value = false } }
async function schedule() { saving.value = true; error.value=''; try { await api.post('/viewings', { ...form.value, scheduledAt: new Date(form.value.scheduledAt).toISOString() }); form.value.scheduledAt=''; form.value.notes=''; await load() } catch (e:any) { error.value = e.response?.data?.message || 'Could not schedule viewing.' } finally { saving.value=false } }
async function updateStatus(item:any, status:string) { try { await api.patch(`/viewings/${item.id}/status`, { status }); await load() } catch (e:any) { error.value=e.response?.data?.message || 'Could not update viewing.' } }
async function cancel(item:any) { try { await api.post(`/viewings/${item.id}/cancel`); await load() } catch(e:any) { error.value=e.response?.data?.message || 'Could not cancel viewing.' } }
function canCancel(item:any){return canRequest.value&&new Date(item.scheduledAt)>new Date()&&['REQUESTED','CONFIRMED'].includes(item.status)}
const date = (d:string) => new Date(d).toLocaleString([], { dateStyle:'medium', timeStyle:'short' })
onMounted(load)
</script>

<template><section class="workspace-content"><div class="section-toolbar"><div><h2>Viewings calendar</h2><p>Schedule in-person tours and video calls, then keep the customer and agent up to date.</p></div><span class="count-pill">{{ viewings.filter((x) => !['COMPLETED','CANCELLED'].includes(x.status)).length }} upcoming</span></div><div v-if="error" class="notice error-notice">{{ error }}</div><div class="split-layout"><form v-if="canRequest" class="panel-card compact-form" @submit.prevent="schedule"><div class="eyebrow muted-eyebrow">REQUEST A VIEWING</div><h3>Choose a time</h3><label>Property<select v-model="form.propertyId" required><option v-for="p in properties" :key="p.id" :value="p.id">{{ p.title }} · {{ p.city }}</option></select></label><label>Date and time<input v-model="form.scheduledAt" required type="datetime-local" /></label><label>Visit type<select v-model="form.mode"><option value="IN_PERSON">In person</option><option value="VIDEO">Video call</option></select></label><label>Notes (optional)<textarea v-model="form.notes" rows="3" placeholder="Preferred time, questions, access needs…"></textarea></label><button class="button button-primary full-button" :disabled="saving || !properties.length">{{ saving ? 'Requesting…' : 'Request viewing' }}</button></form><div class="viewings-list"><div v-if="loading" class="loading-row">Loading your calendar…</div><div v-else-if="!viewings.length" class="empty-state compact-empty"><span class="empty-icon"><CalendarDays /></span><h3>Nothing scheduled yet</h3><p>Your requests and confirmed visits will show up here.</p></div><article v-for="item in viewings" :key="item.id" class="viewing-card"><div class="viewing-date"><b>{{ new Date(item.scheduledAt).toLocaleDateString([], { day:'2-digit' }) }}</b><small>{{ new Date(item.scheduledAt).toLocaleDateString([], { month:'short' }) }}</small></div><div class="viewing-detail"><h3>{{ item.property.title }}</h3><p>{{ item.property.community }}, {{ item.property.city }}</p><div class="viewing-meta"><span><Clock3 :size="14" />{{ date(item.scheduledAt) }}</span><span><Video v-if="item.mode === 'VIDEO'" :size="14" /><CalendarDays v-else :size="14" />{{ item.mode === 'VIDEO' ? 'Video call' : 'In person' }}</span><span v-if="item.requester">{{ item.requester.name }}</span></div></div><div class="viewing-status"><span class="status-pill" :class="item.status.toLowerCase()">{{ item.status }}</span><select v-if="['ADMIN','OWNER','AGENT'].includes(session.session?.user.role || '')" :value="item.status" @change="updateStatus(item, ($event.target as HTMLSelectElement).value)"><option value="REQUESTED">Requested</option><option value="CONFIRMED">Confirm</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancel</option></select><button v-else-if="canCancel(item)" class="button button-outline" @click="cancel(item)">Cancel</button></div></article></div></div></section></template>
